sudo: required
dist: trusty


install:
- nvm install 6
- npm install npm -g
- npm install newman -g
- if [[ "$TRAVIS_TAG" ]]; then npm install --production ; fi
- if [[ "$TRAVIS_BRANCH" ]]; then npm install ; fi
- npm prune

script:
- npm test
- npm run execute 1>/dev/null 2>/dev/null &
- newman -x -c ./test/Test_flightRS.json
#- if [[ "$TRAVIS_TAG" ]]; then npm run dist --production ; fi