sudo: required
dist: trusty


install:
- nvm install 6
- npm install npm -g
- if [[ "$TRAVIS_TAG" ]]; then npm install --production ; fi
- if [[ "$TRAVIS_BRANCH" ]]; then npm install ; fi
- npm prune

script:
- if [[ "$TRAVIS_TAG" ]]; then npm run dist --production ; fi
- if [[ "$TRAVIS_BRANCH" ]]; then npm test ; fi